# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'csv', '3.0.9'
gem 'pry'
gem 'pry-byebug'
gem 'pry-stack_explorer'
